### PR TITLE
add Dockerfile to miniPaint

### PR DESCRIPTION
**Pull request by ghost**
Hello, folks!

This is my first pull-request. I added a Dockerfile from: `https://github.com/bluenevus/docker-minipaint`

*what is Docker?*
Docker is an open platform for developing, shipping, and running applications. Docker enables you to separate your applications from your infrastructure so you can deliver software quickly. With Docker, you can manage your infrastructure in the same ways you manage your applications.

*what is Dockerfile?*
Dockerfile is a text document containing all the commands the user requires to call on the command line to assemble an image. With the help of a Dockerfile, users can create an automated build that executes several command-line instructions in succession.

*why Dockerfile?*
Docker can build images automatically by reading the instructions from a Dockerfile . A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image.

*did you develop and create this config file?*
No. The config file was not created by me, but by [bluenevus/docker-minipaint](https://github.com/bluenevus/docker-minipaint)

*why are you collaborating, helping or maintaining this repository or source code?*
- I hope you like my initial pull-request. 
- There is another pull-request with some feature.
- I would like to help the miniPaint community
- Added this file to increase miniPaint adoption
- As I said initially, I found a default config file for miniPaint with docker. I just added it because I thought it was interesting and doable.
- I thought I'd help since I'm a miniPaint user and I really like the software initially
- There are several configuration files I'm thinking of contributing exclusively to miniPaint like  `.editorconfig`,  `.replit`, `.vercel`, `.netlify`,  `.devContainer`,  `.github`,  `.gitattributes`,  `.render`,  `.goormide`, `.vscode`  - each of these configuration files enable greater adoption of miniPaint.  These files `.replit`, `.vercel`, `.netlify`, `.devContainer` are for just to deploy miniPaint in cloud or any software development platform like Vercel, Codespaces, Repl-it, Netlify, Render, Goorm-Ide etc.

### CODE REVIEW

**Comment by viliusle** [comment]
Can somebody with Docker knowledge review this?

**Comment by Ange-Cesari** [comment]
Hi Ghost and viliusle.

I do have docker knowledge, and it looks not shocking to me. You could make some arrangements, but i'm curious about the centos choice. Why would you use a centos more than an alpine as base image for example ?

The requirements are npm and git. For security purposes you could add the dependencies (and sub dependencies) at the build.

**Comment by tesunaor** [comment]
Hello eveyone!

I'm thinking of helping, I'm thinking of configuring multiple deployment instances:   Vercel, Codespaces, Repl-it, Netlify, Render, Goorm-Ide in miniPaint.

What do you all think of this idea? Is it something interesting or useful for you all?

**Comment by Ange-Cesari** [comment]
Hey,

I wrote a minimalist dockerfile to run miniPaint via docker container.

Simply follow these steps to generate the image yourself: 

pre-requesite : docker & git 

Step 1 : Go into a folder on your local machine and git clone the miniPaint project: 
```bash
git clone https://github.com/viliusle/miniPaint.git
```

Step 2 : Create a dockerfile at the root folder of the project and paste the following code : 

```dockerfile
#Written by Ange Cesari
# Use official Node.js based on Alpine
FROM node:16-alpine

# Create dir for application
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application code
COPY . .

# Expose the port the application will run on
EXPOSE 8080

# Run the application
CMD ["npm", "run", "server"]
```

Step 3 : Build the image : 
```bash
docker build -t minipaint .
```

Step 4 : Once i'ts built, run the container and bind the ports :
```bash
docker run -d -p 8080:8080 --name minipaint-container minipaint
```

Step 5 : Once the container is started, you should be able to reach `http://localhost:8080`

**Comment by viliusle** [comment]
Thank you for contributions.

I added all provided solutions into wiki, so everybody can find it easily. There are multiple versions, so I don't want to move it to main code yet.

https://github.com/viliusle/miniPaint/wiki/Docker

**Comment by raphaellouisandress** [comment]
Please, add docker files miniPaint in [Dockerfiles](https://github.com/michaeljs1990/Dockerfiles)

**Pull request closed without merging**
