### PR TITLE
Rewrite menu from scratch to support mobile sized screens and keyboard controls

### PR DESCRIPTION
**Pull request by Giwayume**
I removed ddsmoothmenu and wrote a custom menu that tries its best to make sure that each menu dropdown stays on screen at all times.

* config-menu.js has changed to a JSON definition that is easier to read and modify.
* Menu dropdowns will open to the left if run out of space on the right. They might overlap if the screen is small enough.
* Menu keyboard controls have been implemented based on WAI ARIA web standards. https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html
* Please test to make sure everything is working as expected. I've covered all the use cases I'm aware of, but could have missed something.

Screenshot from 2020-10-12 01-18-56

### CODE REVIEW

**Comment by Giwayume** [comment]
#167

**Comment by Giwayume** [comment]
Hold up, need to get the translations working again.

**Comment by Giwayume** [comment]
Translations should be good now.

**Comment by viliusle** [comment]
I like it, you can control it using keyboard, it is nice. Also few issues:

- It does not work on IE11. I was supporting IE11 yesterday, but today - not sure if it is worth. It is time to forget this browser. @todo - remove IE11 from readme.md.
- it is very hard to find and focus menu using keyboard only (should be easy to fix to move menu container to the top of main HTML code) - @todo

Did you use any library for `src/js/core/gui/gui-menu.js`? If yes, let me know, i would add link for documentation.

**Comment by Giwayume** [comment]
> I was supporting IE11 yesterday, but today - not sure if it is worth. It is time to forget this browser.
I agree. Even Microsoft Edge has moved to using Chromium as its rendering engine.

> Did you use any library for src/js/core/gui/gui-menu.js? 
No, I wrote the entire thing.

**Pull request merged**
