### PR TITLE
Restyle selection to make it work easier with text and smaller layers

### PR DESCRIPTION
**Pull request by Giwayume**
image

image

- Makes selection outline more visible against both dark and light colors
- Selection outline increases in size when zooming out for visibility
- Resize handles are on the outside of the selection by default so they don't interfere with layer editing
- Handles move inside the layer when near the edge of canvas
- Corner handles are always visible so it never becomes impossible to resize with mouse when very small

### CODE REVIEW

**Comment by viliusle** [comment]
I see multiple problems:

- switch between outside and inside looks weird, inconsistent UI. Most image apps use selectors in middle and it looks less distracting.
- rounded selectors looks much more better, even adobe XD use rounded, while MS paint and PS (i believe PS is old and outdated software, that should not be as example) use rectangles.

Sorry, but i don't want to accept this PR.

**Comment by Giwayume** [comment]
> Most image apps use selectors in middle and it looks less distracting.

What are some examples? I'm trying to fix the problem with it covering up the corners of the layer. It's not just an issue with the text tool, I've had issues with image layers where I needed to see what's in the corner in order to to what I was doing.

> rounded selectors looks much more better

This is more of a usability thing I'm trying to fix than a visual thing. 

Here are some examples of corners being on the outside

Gimp
image

Godot (rounded)
image

The thing is, with these other software the selection works outside the bounds of the canvas so they don't have the issue of not being able to reach the handles on the edges. I'm trying to work around a limitation in miniPaint at the moment.

image

**Comment by Giwayume** [comment]
Adobe XD is a UI prototyping tool, not an image editor. It doesn't have a requirement to make the entire layer visible during editing, because it's more focused on image placement than image editing.

**Comment by Giwayume** [comment]
You like this better?

image

Only the handles that are at the edge of the canvas move inside

image

**Comment by Giwayume** [comment]
Another option with colored borders that's still visible when placed on top of the same color.

image
image

**Comment by viliusle** [comment]
Your explanations makes sense. 

I reverted "Alt color option", we will see how it looks and feels.

**Pull request merged**
